#!/bin/bash

setup=false # Default considers the environment is ready
time=60 # Default time limit for each test
library=false # Should the libraries be installed?
port=$1 # Default serial port connected to the board
test_list=(a v s g)

while test $# -gt 0; do
    echo "$1"
    case "$1" in
        -h|--help)
            echo "Automated testing script"
            echo " "
            echo "./run_script serial-port [options]"
            echo " "
            echo "options:"
            echo "-h, --help          show brief help"
            echo "-t                  specify a time limit for each test"
            echo "-s                  setup environment"
            echo "-l                  Install libraries"
            exit 0
            ;;
        -s) 
            shift
            setup=true
            echo "Setup environment option set"
            ;;
        -l) 
            shift
            library=true
            echo "Libraries installation option set"
            ;;
        -t) 
            shift
            if test $1 -gt 0; then
                time=$1
            else
                echo "ERROR -t : Invalid time"
                exit 1
            fi
            shift
            echo "Time limit set to ${time}"
            ;;
        -f)
            shift
            while [ $# -gt 0 ] && [ ${1::1} != '-' ]; do
                test_list+=('$1')
                shift
            done
            echo $test_list
            ;;
        *)
            break
            ;;
    esac
done

# Theres a couple of things that must be done to prepare the
# testing environment:
# - Install golang and arduino-cli
# - Adding the board and libraries to the cli
# This needs to be done only once.
if [ "$setup" = true ]; then
    set -e # Interrupt if any error ocurrs
    echo "=====> [ PREPARING ENVIRONMENT ] <====="
    
    printf "\n\nUpdating packages....\n\n"
    sudo apt update -y

    printf "\n\nGetting golang....\n\n"
    sudo apt install golang

    printf "\n\nGetting arduino-cli....\n\n"
    go get -u github.com/arduino/arduino-cli

    printf "\n\nReading test environment....\n\n"
    sudo cp ~/go/bin/arduino-cli /bin/
    arduino-cli core update-index

    if [ "$library" = true ]; then
        printf "\n\nInstalling libraries...\n\n"
        while read -r line; do 
            printf "Getting '${line}'\n"
            arduino-cli lib install "$line" > /dev/null   
        done < "libraries.txt"
    fi

    echo "=====> [ READY ] <====="
    exit 0
fi

# In case new libraries are added to libraries.txt,
# simply using the flag -l will install them
if [ "$library" = true ]; then
    printf "\n\nInstalling libraries...\n\n"
    while read -r line; do 
        printf "Getting '${line}'\n"
        arduino-cli lib install "$line" > /dev/null  
    done < "libraries.txt"
fi

# Must receive as the first parameter the path which contains the file to
# where the serial writes from the board are sent (EX: /dev/ttyUSB0)
if [ -z $port ] || [ $(echo $port | head -c 1) = "-" ]; then
    echo ""
    echo "MISSING ARGUMENT: The serial port connected to the board was not defined"
    echo "Try the following:"
    echo " - Run the 'arduino-cli board list' command"
    echo " - Find the row/entry with the desired board"
    echo " - Get the atribute/colunm 'Port' of such row/entry"
    echo " - Pass the atribute as the LAST argument of the script"
    echo ""
    exit 1
fi

# Configure serial port for reading
sudo stty -F $port cs8 115200





printf "\n\nRunning all tests (PORT: $port):\n\n"
for test in ./tests/* ; do
    printf "\n=======> ${test#*/*/}\n"

    printf "\nPreparing Log...\n"
    rm -f logs/${test#*/*/}.log
    touch logs/${test#*/*/}.log
    if [ $? -ne 0 ]; then echo "FAILED to create log, SKIPPING..."; continue; fi

    printf "\nCompiling Test...\n"
    sudo arduino-cli compile -p $port --fqbn esp8266:esp8266:nodemcuv2 $test > /dev/null
    if [ $? -ne 0 ]; then printf "\nFAILED compilation, SKIPPING...\n"; continue; fi

    printf "\nUploading to Board...\n"
    sudo arduino-cli upload -p $port --fqbn esp8266:esp8266:nodemcuv2 $test > /dev/null
    if [ $? -ne 0 ]; then printf "\nFAILED upload, SKIPPING...\n"; continue; fi

    printf "\nRunning ${test}...\n"
    start=$(date +%s)
    while true; do  

        # Update log
        sudo cat $port >> logs/${test#*/*/}.log
        
        # Check for keyword
        if [ ! -z "$(tail -1 logs/${test#*/*/}.log | grep -w "Pass")" ]; then    
            echo "PASSED!!!"
            break
        elif [ ! -z "$(tail -1 logs/${test#*/*/}.log | grep -w "Fail")" ]; then
            echo "FAILED!!!"
            break
        fi

        if [ $(($(date +%s) - start)) -gt $time ]; then
            echo "TIMEOUT: The time limit of ${time}s was exceeded."
            echo " - Try incresing the time limit with the flag '-t'"
            echo " - Check if the test is serial printing the keywords (Pass/Fail)"
            break
        fi

    done

done